name: Sync from Github Org Dispersia

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add org remote
        run: |
          git remote add org-origin https://${{ secrets.DISPERSIA_PAT }}@github.com/dispersia-id/dispersia.git

      - name: Fetch from org repo
        env:
          PAT: ${{ secrets.DISPERSIA_PAT }}
        run: |
          git fetch org-origin
          git pull org-origin master --rebase
          
      - name: Push to repo
        run: |
          git push origin master
